const ACTIONS = {
    SET_REDIRECTION: 'SET_REDIRECTION',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_TOKEN: 'SET_TOKEN',
    SET_ROOMS: 'SET_ROOMS',
    ADD_CHAT: 'ADD_CHAT'
};

export default ACTIONS;